######################################################################
# Automatically generated by qmake (3.0) Wed Oct 14 04:35:43 2015
######################################################################

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

QT += gui core
QT += widgets

# Input
SOURCES += main.cpp \
    sniff.cpp \
    mainwindow.cpp

HEADERS += \
    sniff.h \
    mainwindow.h

FORMS += \
    mainwindow.ui
